### ISSUE TITLE
Organization Home Page

### ISSUE THREAD

**Issue by awjans** [ingeniouspartners/ingeniouspartners.github.io#2]
Do all work for this task in a branch called issue-02

Make sure it meets the requirement for E56 and E58, be creative, check out other themes, etc.
Coordinate with Ursula

**Comment by mikhail-shkaralevich** [comment]
2-3 hours is my estimate for this issue.

**Comment by mikhail-shkaralevich** [comment]
It took me 4 hours to complete. I had to deal with HTML&CSS to get the look i wanted. Markdown was not enough.
